# Creating a Simple neuron network

In [1]:
import numpy as np

# define a basic sigmoid funtion

In [2]:
def sigmoid(x):
    return 1 / (1+ np.exp(-x))

# definge sigmoid_derivative function for adjustments of weights later

def sigmoid_derivative(x):
    return x * (1-x)

# define the inputs neural network

In [3]:
training_inputs = np.array([[0,0,1],
                           [1,1,1],
                           [1,0,1],
                           [0,1,1]])

training_outputs = np.array([[0,1,1,0]]).T

# Initializing random weights

In [4]:
np.random.seed(1)

In [5]:
synaptic_weights = 2 * np.random.random((3,1)) - 1

In [6]:
print('Random starting synaptic weights')
print(synaptic_weights)

Random starting synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [7]:
for iteration in range(20000):
    
    input_layer = training_inputs
    
    outputs = sigmoid(np.dot(input_layer, synaptic_weights))
    
    # calculate the error
    error = training_outputs - outputs
    
    # caluculate the adjustment for weights using sigmoid_derivative defined above
    adjustments = error * sigmoid_derivative(outputs)
    
    # Adjust the synaptic_weights 
    synaptic_weights += np.dot(input_layer.T, adjustments)
    
print('Synaptic weights after training')
print(synaptic_weights)
    
print('Output after training')
print(outputs)

Synaptic weights after training
[[10.38040701]
 [-0.20641179]
 [-4.98452047]]
Output after training
[[0.00679672]
 [0.99445583]
 [0.99548516]
 [0.00553614]]


the outputs are very close to our outputs --> 0,1,1,0